/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.paingan.chart;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.paingan.chart.domain.ReportData;
import org.paingan.chart.dao.ReportDataDao;

/**
 *
 * @author paulusyansen
 */
public class ChartMainFrame extends javax.swing.JFrame {
private DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form ChartDataFrame
     */
    public ChartMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSite = new javax.swing.ButtonGroup();
        jsp = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        lblSite = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weekly Site Speed Report");
        setResizable(false);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jsp.setViewportView(tblData);

        bgSite.add(rb1);
        rb1.setSelected(true);
        rb1.setText("elevenia");

        bgSite.add(rb2);
        rb2.setText("lazada");

        bgSite.add(rb3);
        rb3.setText("tokopedia");

        lblSite.setText("Site");

        lblDate.setText("Date");

        lblScore.setText("Score");

        btnReport.setText("Report");
        btnReport.setEnabled(false);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnSave.setText("Add");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblType.setText("Type");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Type", "alexa", "4G" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblType)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(22, 22, 22)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReport))
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(lblSite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScore)
                    .addComponent(btnReport)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        String type = (String) cmbType.getSelectedItem();
        
        if("4G".equals(type)){
            ChartReportFrame mainFrame = new ChartReportFrame("4G");
            mainFrame.setVisible(true);
        } else {
            ChartReportFrame mainFrame = new ChartReportFrame("alexa");
            mainFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if("".equals(txtDate.getText()) && "".equals(txtScore.getText())) {
            JOptionPane.showMessageDialog(null, "Date or Score is Empty!");
            return;
        }
        
        model = new DefaultTableModel();
        tblData.setModel(model);
            
        ReportDataDao dataCrud = new ReportDataDao();
        dataCrud.openConnection();
        
        String type = (String) cmbType.getSelectedItem();
        
        List<ReportData> reportList = new ArrayList();
        
        ReportData reportData = new ReportData();
        
        String site = "";
        
        for (Enumeration<AbstractButton> buttons = bgSite.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                site = button.getText();
            }
        }
         
        reportData.setDate(txtDate.getText());
        reportData.setScore(Float.parseFloat(txtScore.getText()));
        reportData.setSite(site);
        
        
        if("alexa".equals(type)){
            try {
                reportList = dataCrud.getAlexaList();
                dataCrud.insertAlexa(reportData);
            } catch (SQLException ex) {
                Logger.getLogger(ChartMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if("4G".equals(type)){
            try {
                reportList = dataCrud.get4GList();
                dataCrud.insertAlexa(reportData);
            } catch (SQLException ex) {
                Logger.getLogger(ChartMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //TODO add save action
        
        

        for (ReportData data : reportList) {
            model.addRow(new Object[]{ data.getDate(), data.getSite(), data.getScore() });
        }
        
        
        dataCrud.closeConnection();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String type = (String)cb.getSelectedItem();
        System.out.println(type);
        
        if("alexa".equals(type)){
            model = new DefaultTableModel();
            tblData.setModel(model);
            
            model.addColumn("Date");
            model.addColumn("Site");
            model.addColumn("Score");
            tblData.setModel(model);

            ReportDataDao dataCrud = new ReportDataDao();
            dataCrud.openConnection();
            List<ReportData> alexaList = dataCrud.getAlexaList();

            for (ReportData reportData : alexaList) {
                model.addRow(new Object[]{ reportData.getDate(), reportData.getSite(), reportData.getScore() });
            }

            dataCrud.closeConnection();
            
            btnSave.setEnabled(true);
            btnReport.setEnabled(true);
        }
        else if("4G".equals(type)){
            model = new DefaultTableModel();
            tblData.setModel(model);
            
            model.addColumn("Date");
            model.addColumn("Site");
            model.addColumn("Score");
            tblData.setModel(model);

            ReportDataDao dataCrud = new ReportDataDao();
            dataCrud.openConnection();
            List<ReportData> reportList = dataCrud.get4GList();

            for (ReportData reportData : reportList) {
                model.addRow(new Object[]{ reportData.getDate(), reportData.getSite(), reportData.getScore() });
            }

            dataCrud.closeConnection();
            
            btnSave.setEnabled(true);
            btnReport.setEnabled(true);
        } else {
            model = new DefaultTableModel();
            tblData.setModel(model);
            
            btnSave.setEnabled(false);
            btnReport.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSite;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
