/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.paingan.chart;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.RangeType;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.RectangleInsets;
import org.paingan.chart.domain.Alexa;
import org.paingan.chart.dao.AlexaDao;

/**
 *
 * @author paulusyansen
 */
public class ChartReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChartMainFrame
     */
    public ChartReportFrame() {
        DefaultCategoryDataset alexaSeries = new DefaultCategoryDataset();
         
        AlexaDao dataCrud = new AlexaDao();
        dataCrud.openConnection();
        List<Alexa> alexaList = dataCrud.getAlexaList();
        dataCrud.closeConnection();
         
        for (Alexa alexa : alexaList) {
            alexaSeries.addValue(alexa.getScore(),alexa.getSite(),alexa.getDate());
        }
         
        //XYDataset xyDataset = xySeriesCollection;
        JFreeChart chart = ChartFactory.createLineChart(
            "Site Speed (Alexa)",  "", "Average Load Time",
            alexaSeries, PlotOrientation.VERTICAL, true, true, false);
        
        
        CategoryPlot plot = chart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(0, Color.ORANGE);
        plot.getRenderer().setSeriesStroke(0, new BasicStroke( 3 ));
        plot.getRenderer().setSeriesPaint(1, Color.BLUE);
        plot.getRenderer().setSeriesStroke(1, new BasicStroke( 3 ));
        plot.getRenderer().setSeriesPaint(2, Color.GREEN);
        plot.getRenderer().setSeriesStroke(2, new BasicStroke( 3 ));
//        plot.getRenderer().setBaseToolTipGenerator(new StandardCategoryToolTipGenerator(
//    "Series {0}, Category {1}, Value {2}", NumberFormat.getInstance()));
        
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
//        rangeAxis.setRange(1.5, 3.5);
        rangeAxis.setInverted(true);
        rangeAxis.setAutoRange(false);
        rangeAxis.setRangeWithMargins(1.4,3.4);
        rangeAxis.setTickUnit(new NumberTickUnit(0.1));
        
        NumberFormat formatter = new DecimalFormat("#0.00");     
        rangeAxis.setNumberFormatOverride(formatter);
//        rangeAxis.setAxisLinePaint(Color.RED);
//        plot.getRangeAxis();
//NumberAxis rangeAxis = (NumberAxis)p lot.getRangeAxis();
//rangeAxis.setAxisRange(0.0, 100.0);
      
        Color mycolor = new Color(240,240,240); 
        plot.setBackgroundPaint(mycolor);
        
        /* generate chart image */
        int width = 1024;    /* Width of the image */
        int height = 600;   /* Height of the image */ 
        File lineChart = new File( "LineChart.jpeg" ); 
        
        try {
            ChartUtilities.saveChartAsJPEG(lineChart ,chart, width ,height);
        } catch (IOException ex) {
            Logger.getLogger(ChartReportFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ChartPanel cp = new ChartPanel(chart) {
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(1024, 600);
            }
        };
    
        add(cp);

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chart Sample using JFreeChart");
        setName("frmMain"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartReportFrame().setVisible(true);
            }
        });
    }
    
   private DefaultCategoryDataset createDataset( ) {
      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
      dataset.addValue( 15 , "schools" , "1970" );
      dataset.addValue( 30 , "schools" , "1980" );
      dataset.addValue( 60 , "schools" ,  "1990" );
      dataset.addValue( 120 , "schools" , "2000" );
      dataset.addValue( 240 , "schools" , "2010" );
      dataset.addValue( 300 , "schools" , "2014" );
      
      dataset.addValue( 153 , "schoolss" , "1970" );
      dataset.addValue( 36 , "schoolss" , "1980" );
      dataset.addValue( 69 , "schoolss" ,  "1990" );
      dataset.addValue( 121 , "schoolss" , "2000" );
      dataset.addValue( 245 , "schoolss" , "2010" );
      dataset.addValue( 400 , "schoolss" , "2014" );
      return dataset;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
